import { readFile, writeFile } from "node:fs/promises";

// Deliberately limited to this repository's named imports/exports, not a general
// JavaScript bundler. No dependencies, timestamps, network, or minification.
const root = new URL("../", import.meta.url);
const files = ["coordinates", "parse", "page", "api", "standalone"];
const parts = [];
for (const file of files) {
  let source = await readFile(new URL(`src/${file}.js`, root), "utf8");
  source = source.replace(/^import \{[^\n]+\} from "\.\/[^"\n]+\.js";\n/gm, "");
  source = source.replace(/^export \{[^\n]+\} from "\.\/[^"\n]+\.js";\n/gm, "");
  source = source.replace(/^export (?=(?:async )?function |const )/gm, "");
  if (/^import\s/m.test(source) || /^export (?!default\s*\{)/m.test(source)) {
    throw new Error(`Unsupported module syntax in src/${file}.js; update the build script explicitly`);
  }
  parts.push(`// ---- src/${file}.js ----\n${source.trimEnd()}\n`);
}
const output = "// GENERATED by npm run build from src/. Do not edit this file directly.\n\n" + parts.join("\n");
const destination = new URL("wloc-worker.js", root);
if (process.argv.includes("--check")) {
  if (await readFile(destination, "utf8") !== output) {
    throw new Error("wloc-worker.js is out of date; run npm run build");
  }
  console.log("wloc-worker.js matches source");
} else {
  await writeFile(destination, output);
  console.log("Generated wloc-worker.js");
}
